export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const NAVIGATION_TOGGLE_MENU = 'NAVIGATION_TOGGLE_MENU';
export const NAVIGATION_TOGGLE_AUTH = 'NAVIGATION_TOGGLE_AUTH';
